site_name: DataHandler
site_url: https://mattschrubb.github.io/DataHandler
repo_name: MadStudioRoblox/ReplicaService
repo_url: https://github.com/MattSchrubb/DataHandler

theme:
  name: material
  palette:
    primary: "indigo"
    accent: "indigo"

nav:
  - API: api.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
